# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('number', models.IntegerField(default=0)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routeplanning.Line')),
            ],
        ),
    ]
