# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0002_linepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('origin', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('departure_time', models.TimeField(auto_now=True)),
                ('arrival_time', models.TimeField(auto_now=True)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routeplanning.Line')),
            ],
        ),
    ]
