# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0004_flight_weekly_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField(default=0)),
                ('departure_datetime', models.DateTimeField()),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routeplanning.Flight')),
                ('tail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routeplanning.Tail')),
            ],
        ),
    ]
