# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0006_auto_20170329_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='departure_datetime',
        ),
        migrations.AddField(
            model_name='assignment',
            name='end_time',
            field=models.DateTimeField(default='2017-03-30 00:00:00+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_time',
            field=models.DateTimeField(default='2017-03-30 00:00:00+00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='tail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routeplanning.Tail'),
        ),
    ]
