# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0009_auto_20170330_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='line',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_datetime',
            field=models.DateTimeField(default='2017-01-01 00:00:00+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_datetime',
            field=models.DateTimeField(default='2017-01-01 00:00:00+00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='number',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
