# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0010_auto_20170403_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='weekly_availability',
        ),
    ]
