# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0011_remove_flight_weekly_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linepart',
            name='name',
        ),
    ]
