# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0012_remove_linepart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='flight_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='number',
            field=models.CharField(db_index=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='linepart',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
