# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0014_auto_20170411_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='routeplanning.Flight'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='tail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='routeplanning.Tail'),
        ),
    ]
