# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0015_auto_20170426_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='flight',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='routeplanning.Flight'),
        ),
    ]
