# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0017_hobbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbs',
            name='name',
        ),
        migrations.AddField(
            model_name='hobbs',
            name='hobbs',
            field=models.IntegerField(default=0),
        ),
    ]
