# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0018_auto_20170504_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbs',
            name='hobbs',
            field=models.FloatField(default=0.0),
        ),
    ]
