# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0019_auto_20170504_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbs',
            name='flight',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='routeplanning.Flight'),
        ),
    ]
