# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0020_hobbs_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnscheduledFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='unscheduled_flight',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='routeplanning.UnscheduledFlight'),
        ),
    ]
