# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-12 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0021_auto_20170511_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='unscheduled_flight',
        ),
        migrations.AddField(
            model_name='flight',
            name='type',
            field=models.IntegerField(choices=[(1, 'Scheduled Flight'), (2, 'Unscheduled Flight')], default=1),
        ),
        migrations.DeleteModel(
            name='UnscheduledFlight',
        ),
    ]
