# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0022_auto_20170511_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tail',
            name='number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
