# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0024_auto_20170606_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision',
            old_name='created',
            new_name='published_datetime',
        ),
    ]
