# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0025_auto_20170606_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revision',
            name='has_draft',
            field=models.BooleanField(default=False),
        ),
    ]
