# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-07 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0026_auto_20170606_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='routeplanning.Flight'),
        ),
    ]
