# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-08 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0027_auto_20170606_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbs',
            name='flight',
        ),
    ]
