# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0028_remove_hobbs_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='actual_in_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='actual_off_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='actual_on_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='actual_out_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='scheduled_off_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='scheduled_on_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
