# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0030_auto_20170710_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='actual_in_datetime',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='actual_off_datetime',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='actual_on_datetime',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='actual_out_datetime',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='estimated_in_datetime',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='estimated_off_datetime',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='estimated_on_datetime',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='estimated_out_datetime',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='scheduled_off_datetime',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='scheduled_on_datetime',
        ),
        migrations.AddField(
            model_name='flight',
            name='actual_in_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='actual_off_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='actual_on_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='actual_out_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='estimated_in_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='estimated_off_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='estimated_on_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='estimated_out_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='scheduled_off_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='scheduled_on_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
