# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplanning', '0032_auto_20170710_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='scheduled_in_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_out_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
