version: '2.1'
services:
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "80:8001"
    volumes:
      - .:/code
      - ./deploy/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    container_name: dg01
    command: bash -c "chmod +x ./deploy/start-server.sh && ./deploy/start-server.sh"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: ps01
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"