# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_auto_20170524_0222'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inspectiontask',
            table='inspection_task',
        ),
    ]
