# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_auto_20170524_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('interval', models.IntegerField(default=0)),
                ('interval_unit', models.CharField(default='hours', max_length=10)),
            ],
            options={
                'db_table': 'inspection_component',
            },
        ),
        migrations.RemoveField(
            model_name='inspectionprogram',
            name='number',
        ),
        migrations.RemoveField(
            model_name='inspectiontask',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='inspectiontask',
            name='interval_unit',
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspectioncomponent',
            name='inspection_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.InspectionTask'),
        ),
    ]
