# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_auto_20170524_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionprogram',
            name='inspection_tasks',
            field=models.ManyToManyField(to='inspection.InspectionTask'),
        ),
    ]
