# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_inspectionprogram_inspection_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionComponentSubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'MOS'), (2, 'HRS'), (3, 'AFL')], default=1)),
                ('interval', models.IntegerField()),
                ('CW', models.CharField(blank=True, default='', max_length=50)),
                ('TSX_adj', models.CharField(blank=True, default='', max_length=50)),
                ('max_limit', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'inspection_component_sub_item',
            },
        ),
        migrations.RemoveField(
            model_name='inspectioncomponent',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='inspectioncomponent',
            name='interval_unit',
        ),
        migrations.AddField(
            model_name='inspectioncomponentsubitem',
            name='inspection_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.InspectionComponent'),
        ),
        migrations.AddField(
            model_name='inspectioncomponentsubitem',
            name='inspection_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.InspectionTask'),
        ),
    ]
