# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_auto_20170526_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionComponentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(blank=True, max_length=30)),
                ('sn', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'inspection_component_sub_item_template',
            },
        ),
        migrations.RemoveField(
            model_name='inspectioncomponentsubitem',
            name='inspection_component',
        ),
        migrations.RemoveField(
            model_name='inspectioncomponentsubitem',
            name='inspection_task',
        ),
        migrations.AddField(
            model_name='inspectioncomponent',
            name='pn',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='inspectioncomponent',
            name='sn',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='InspectionComponentSubItem',
        ),
        migrations.AddField(
            model_name='inspectioncomponenttemplate',
            name='inspection_component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.InspectionComponent'),
        ),
    ]
