# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_auto_20170526_0601'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inspectioncomponenttemplate',
            table='inspection_component_template',
        ),
    ]
