# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_auto_20170526_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectioncomponenttemplate',
            name='inspection_component',
        ),
        migrations.AddField(
            model_name='inspectioncomponenttemplate',
            name='inspection_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.InspectionTask'),
        ),
    ]
