# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspection', '0011_auto_20170526_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(max_length=20)),
                ('serial', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('reported_date', models.DateTimeField(blank=True)),
                ('inspection_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.InspectionProgram')),
            ],
            options={
                'db_table': 'aircraft',
            },
        ),
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'aircraft_type',
            },
        ),
        migrations.CreateModel(
            name='Airframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.IntegerField(default=0)),
                ('reported_hours', models.IntegerField(default=0)),
                ('reported_landings', models.IntegerField(default=0)),
                ('last_inspection_time', models.DateTimeField(blank=True, null=True)),
                ('aircraft', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Aircraft')),
            ],
            options={
                'db_table': 'airframe',
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('engine_hours', models.IntegerField(blank=True, default=0, null=True)),
                ('engine_cycles', models.IntegerField(blank=True, default=0, null=True)),
                ('last_hot_section_time', models.DateTimeField(blank=True)),
                ('last_overhaul_time', models.DateTimeField(blank=True)),
                ('tbo', models.IntegerField(blank=True, default=0, null=True)),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Aircraft')),
            ],
            options={
                'db_table': 'engine',
            },
        ),
        migrations.CreateModel(
            name='InspectionComponentSubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'MOS'), (2, 'HRS'), (3, 'AFL')], default=1)),
                ('interval', models.IntegerField()),
                ('CW', models.CharField(blank=True, default='', max_length=50)),
                ('TSX_adj', models.CharField(blank=True, default='', max_length=50)),
                ('max_limit', models.CharField(blank=True, default='', max_length=50)),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Aircraft')),
                ('inspection_component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspection.InspectionComponent')),
            ],
            options={
                'db_table': 'inspection_component_sub_item',
            },
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=500)),
                ('onsip', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'personal_data',
                'verbose_name_plural': 'personal data',
            },
        ),
        migrations.CreateModel(
            name='Propeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_inspection_time', models.DateTimeField(blank=True)),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Aircraft')),
            ],
            options={
                'db_table': 'propeller',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('personal_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.PersonalData')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('access', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.UserRole'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.AircraftType'),
        ),
    ]
