# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
