FLIGHT_TYPE_SCHEDULED = 1
FLIGHT_TYPE_UNSCHEDULED = 2


FLIGHT_TYPE_CHOICES = (
    (FLIGHT_TYPE_SCHEDULED, 'Scheduled Flight'),
    (FLIGHT_TYPE_UNSCHEDULED, 'Unscheduled Flight'),
)


ASSIGNMENT_STATUS_FLIGHT = 1
ASSIGNMENT_STATUS_MAINTENANCE = 2
ASSIGNMENT_STATUS_UNSCHEDULED_FLIGHT = 3


ASSIGNMENT_STATUS_CHOICES = (
    (ASSIGNMENT_STATUS_FLIGHT, 'Flight'),
    (ASSIGNMENT_STATUS_MAINTENANCE, 'Maintenance'),
    (ASSIGNMENT_STATUS_UNSCHEDULED_FLIGHT, 'Unscheduled Flight'),
)


HOBBS_TYPE_ACTUAL = 1
HOBBS_TYPE_NEXT_DUE = 2


HOBBS_TYPE_CHOICES = (
    (HOBBS_TYPE_ACTUAL, 'Actual'),
    (HOBBS_TYPE_NEXT_DUE, 'Next Due'),
)


ASSIGNMENT_RESIZE_POSITION_CHOICES = (
    ('start', 'Start'),
    ('end', 'End'),
)
